In [1]:
import datetime
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, \
                            mean_squared_error, median_absolute_error, accuracy_score
import numpy as np
#from pmdarima.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
#from pmdarima import auto_arima
import numpy as np
import sklearn.metrics
import sklearn

## Regressão linear
from sklearn.linear_model import LinearRegression

## Gradient Boosting
from xgboost import XGBRegressor

In [9]:
df_model = pd.read_csv('../datasets/df_modelo_pa_diario.csv', sep=';')

In [13]:
df_model['UF_GrpProd'] = df_model['UF'].map(str) + '-' + df_model['GrpProd'].map(str)

In [14]:
df_model

       GrpProd  UF   Ano  Mes  Dia  QTD  Preço   CMV/QTD  DPPsic UF_GrpProd
0          0.0  AC  2017    1   20  4.0   7.99  4.385000     1.0     AC-0.0
1          0.0  AC  2017    1   22  5.0   7.99  4.384000     1.0     AC-0.0
2          0.0  AC  2017    3   31  4.0   4.99  4.320000     1.0     AC-0.0
3          0.0  AC  2017    4    2  3.0   4.99  4.316667     1.0     AC-0.0
4          0.0  AC  2017    4    5  3.0   4.99  4.320000     1.0     AC-0.0
...        ...  ..   ...  ...  ...  ...    ...       ...     ...        ...
23262      7.0  TO  2017   12   26  4.0   3.99  1.907500     1.0     TO-7.0
23263      7.0  TO  2017   12   28  2.0   3.99  1.930000     1.0     TO-7.0
23264      7.0  TO  2017   12   29  2.0   3.99  1.845000     1.0     TO-7.0
23265      7.0  TO  2017   12   30  5.0   3.99  1.900000     1.0     TO-7.0
23266      7.0  TO  2017   12   31  2.0   3.99  1.915000     1.0     TO-7.0

[23267 rows x 10 columns]

In [3]:
scoring = ['neg_mean_absolute_error', 'neg_mean_absolute_percentage_error']
refit_value = 'neg_mean_absolute_percentage_error'

## Regressão linear
lrParams = {"fit_intercept": [True, False], 
              "copy_X":[True, False], 
              "n_jobs":[1,2,None], 
              "positive":[True, False]}


## Gradient Boosting
GBSearchSpace = {"n_estimators": [20, 50], 
              "max_depth":[3,6], 
              "gamma":[0.01,0.1], 
              "learning_rate":[0.001,0.01,1]}

xgb = XGBRegressor(random_state=100)

In [17]:
def modelos(dataframe, var_expl):
    """
    Retorna a quantidade de itens que serão vendidos dado um preço
    
    params: dataframe -> Dataframe sobre o qual será feita a regressão linear
            var_expl -> recebe as variáveis explicativas (str ou listas de strings)
    """
    
    results = {'Ajuste':[], 'Previsoes':[]}
    
    results_reg = {'Serie':[], 'Intercept':[], 'Coef':[], 'MAE':[], 'MAPE':[]}
    #results_regGB = {'Serie':[], 'Intercept':[], 'Coef':[], 'MAE':[], 'MAPE':[]}
    
    df = pd.DataFrame(data=None, columns=df_model.columns)
    df['VendasPrevistas'] = ''
    df['NomeModelo'] = ''

    for comb in dataframe['UF_GrpProd'].unique():

        if isinstance(var_expl, str):
            X = np.array(dataframe.loc[dataframe["UF_GrpProd"] == comb][var_expl]).reshape(-1,1)
        else:
            X = np.array(dataframe.loc[dataframe["UF_GrpProd"] == comb][var_expl])

            Y = np.array(dataframe.loc[dataframe["UF_GrpProd"] == comb]["QTD"]).reshape(-1, 1)
            

            ## Linear Regression
            LRGridSearch = GridSearchCV(estimator = LinearRegression(),
                                       param_grid = lrParams,
                                       scoring = scoring,
                                       refit = refit_value)
            
            ## Gradient Boosting
            GS_xgb =  GridSearchCV(estimator = xgb,
                      param_grid = GBSearchSpace,
                      scoring = scoring, #definido na primeira versão
                      refit = refit_value,#definido na primeira versão
                      cv=4,
                      verbose = 0) #número de informações a serem impressas a cada iteração 
            
            
            ## Ajustando o modelo Linear Regression
            lr = LRGridSearch.fit(X, Y)
            
            ## Ajustando o modelo Gradient Boosting
            gb = GS_xgb.fit(X ,Y)
            
            
            
            ## Encontrando MAPE de Linear Regression
            mapeLR = lr.best_score_
            
            ## Encontrando MAPE de Linear Regression
            mapeGB = gb.best_score_
            
            
            dfteste = dataframe.loc[dataframe["UF_GrpProd"] == comb].copy()
            
            
            ## Decidindo qual modelo será utilizado para fazer a predição
            if mapeLR < mapeGB:
                predict = lr.predict(X)
                dfteste['NomeModelo'] = 'LR'
            
            else:
                predict = gb.predict(X)
                dfteste['NomeModelo'] = 'XGB'
            
            
            dfteste['VendasPrevistas'] = predict
            df = pd.concat([df, dfteste])
            
            mape = mean_absolute_percentage_error(dfteste["QTD"], dfteste["VendasPrevistas"])
            
            results_reg["Serie"].append(comb)
            results_reg["Intercept"].append(lr.best_estimator_.intercept_)
            results_reg["Coef"].append(lr.best_estimator_.coef_)
            results_reg['MAE'].append(lr.best_score_)
            results_reg['MAPE'].append(mean_absolute_percentage_error(dfteste["QTD"], 
                                                                      dfteste["VendasPrevistas"]))
            

    df_coeficientes = pd.DataFrame(results_reg)
    df_coeficientes = df_coeficientes.explode('Coef')
    df_coeficientes['Intercept'] = df_coeficientes['Intercept'].astype(float)
    num_coef = len(df_coeficientes["Coef"][0])
    a = np.array(df_coeficientes["Coef"].explode()).reshape(df_coeficientes.shape[0], num_coef)
    df__ = pd.DataFrame(a, columns = ["Coef1", "Coef2"])
    df_coeficientes = df_coeficientes.merge(df__, left_index = True, right_index = True)
    df_coeficientes = df_coeficientes.drop(columns = "Coef")
    
    df_coeficientes = df_coeficientes[["Serie", "Intercept", "Coef1", "Coef2", "MAE", "MAPE"]]
    
    #df = df.style.set_properties(**{'text-align': 'left'})
    #df_coeficientes = df_coeficientes.style.set_properties(**{'text-align': 'left'})
    
    results["Ajuste"].append(df)
    results["Previsoes"].append(df_coeficientes)
    
    df['VendasPrevistas'] = df['VendasPrevistas'].apply(lambda x: round(x))
    
    return df

In [18]:
df_predicoes = modelos(df_model, ['Preço', 'CMV/QTD'])

In [20]:
df_predicoes

,GrpProd,UF,Ano,Mes,Dia,QTD,Preço,CMV/QTD,DPPsic,UF_GrpProd,VendasPrevistas,NomeModelo
0,0.0,AC,2017,1,20,4.0,7.99,4.385000,1.0,AC-0.0,8,LR
1,0.0,AC,2017,1,22,5.0,7.99,4.384000,1.0,AC-0.0,8,LR
2,0.0,AC,2017,3,31,4.0,4.99,4.320000,1.0,AC-0.0,11,LR
3,0.0,AC,2017,4,2,3.0,4.99,4.316667,1.0,AC-0.0,11,LR
4,0.0,AC,2017,4,5,3.0,4.99,4.320000,1.0,AC-0.0,11,LR
...,...,...,...,...,...,...,...,...,...,...,...,...
23262,7.0,TO,2017,12,26,4.0,3.99,1.907500,1.0,TO-7.0,4,LR
23263,7.0,TO,2017,12,28,2.0,3.99,1.930000,1.0,TO-7.0,4,LR
23264,7.0,TO,2017,12,29,2.0,3.99,1.845000,1.0,TO-7.0,4,LR
23265,7.0,TO,2017,12,30,5.0,3.99,1.900000,1.0,TO-7.0,4,LR
23266,7.0,TO,2017,12,31,2.0,3.99,1.915000,1.0,TO-7.0,4,LR

In [23]:
df_predicoes.sort_values(by=['Dia', 'Mes'])

,GrpProd,UF,Ano,Mes,Dia,QTD,Preço,CMV/QTD,DPPsic,UF_GrpProd,VendasPrevistas,NomeModelo
102,0.0,AL,2017,2,1,10.0,7.990000,4.309000,1.0,AL-0.0,14,LR
322,0.0,AM,2017,2,1,16.0,7.990000,3.403750,1.0,AM-0.0,22,LR
505,0.0,AP,2017,2,1,8.0,7.990000,3.643750,1.0,AP-0.0,12,LR
681,0.0,BA,2017,2,1,93.0,7.817957,3.260430,0.0,BA-0.0,121,LR
982,0.0,CE,2017,2,1,33.0,7.965758,3.987576,0.0,CE-0.0,52,LR
...,...,...,...,...,...,...,...,...,...,...,...,...
20007,7.0,DF,2017,12,31,6.0,3.990000,1.908333,1.0,DF-7.0,8,LR
20515,7.0,MA,2017,12,31,5.0,3.990000,1.818000,1.0,MA-7.0,7,LR
22367,7.0,RO,2017,12,31,2.0,3.990000,1.830000,1.0,RO-7.0,4,LR
23143,7.0,SP,2017,12,31,11.0,3.990000,2.242727,1.0,SP-7.0,23,LR
23266,7.0,TO,2017,12,31,2.0,3.990000,1.915000,1.0,TO-7.0,4,LR

In [11]:
df_model

       GrpProd  UF   Ano  Mes  Dia  QTD  Preço   CMV/QTD  DPPsic
0          0.0  AC  2017    1   20  4.0   7.99  4.385000     1.0
1          0.0  AC  2017    1   22  5.0   7.99  4.384000     1.0
2          0.0  AC  2017    3   31  4.0   4.99  4.320000     1.0
3          0.0  AC  2017    4    2  3.0   4.99  4.316667     1.0
4          0.0  AC  2017    4    5  3.0   4.99  4.320000     1.0
...        ...  ..   ...  ...  ...  ...    ...       ...     ...
23262      7.0  TO  2017   12   26  4.0   3.99  1.907500     1.0
23263      7.0  TO  2017   12   28  2.0   3.99  1.930000     1.0
23264      7.0  TO  2017   12   29  2.0   3.99  1.845000     1.0
23265      7.0  TO  2017   12   30  5.0   3.99  1.900000     1.0
23266      7.0  TO  2017   12   31  2.0   3.99  1.915000     1.0

[23267 rows x 9 columns]

In [24]:
df_predicoes.groupby(['NomeModelo'])['NomeModelo'].count()

NomeModelo
LR     22505
XGB      762
Name: NomeModelo, dtype: int64