## Descrição do Notebook

Este é um notebook somente para **EDA**. Os tratamentos feitos aqui foram feitos sobre os dados brutos iniciais e o *dataset* final gerado não foi utilizado como base na expansão dos dados.

In [28]:
import pandas as pd
import xlrd

from fuzzywuzzy import process
import numpy as np
import datetime

### Leitura  e observação do df principal

In [29]:
df_tratado = pd.read_csv('../datasets/df_rpo_v4_dia.csv')
df_tratado.shape

(104186, 15)

## Filtrar ano de 2017

In [30]:
df_tratado = df_tratado.loc[df_tratado["Ano"]==2017]

In [31]:
df_tratado

,SAP+NOME,UF,Dia,Mes,Ano,preço2,Mg %,Margem Líquida Real %,Preço,Vendas Reais Qtde,Vendas Reais $,Margem Líquida Real $,Venda Líquida Real $,CMV,CMV/QTD
0,000000000004243420 - AMACIANTE COMFORT CONCENT...,AL,2,1,2017,7.99,0.407011,40.701149,7.990,12.0,95.88,35.41,87.00,51.59,4.299167
1,000000000004243420 - AMACIANTE COMFORT CONCENT...,AM,2,1,2017,7.99,0.554937,55.493749,7.865,24.0,188.76,104.75,188.76,84.01,3.500417
2,000000000004243420 - AMACIANTE COMFORT CONCENT...,AP,2,1,2017,7.99,0.499373,49.937312,7.990,11.0,87.89,39.83,79.76,39.93,3.630000
3,000000000004263231 - JG CAMA QUEEN PRATA 150FI...,AP,2,1,2017,129.99,0.498731,49.873123,129.990,1.0,129.99,47.17,94.58,47.41,47.410000
4,000000000002158151 - T VISITA P BORDA DESIRE A...,BA,2,1,2017,4.99,0.416721,41.672131,4.190,10.0,41.90,12.71,30.50,17.79,1.779000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34581,000000000002166665 - FRONHA AVULSA ESTAMPADA A...,TO,31,12,2017,4.99,0.397732,39.773237,4.990,43.0,214.57,62.09,156.11,94.02,2.186512
34582,000000000002166719 - FRONHA AVULSA LISA ANDREZA,TO,31,12,2017,4.99,0.412655,41.265475,4.990,4.0,19.96,6.00,14.54,8.54,2.135000
34583,000000000004261082 - KIT CABIDE C/3 MADEIRA REV,TO,31,12,2017,1.99,0.146507,14.650706,10.990,14.0,153.86,16.40,111.94,95.54,6.824286
34584,000000000004266282 - JG CAMA QUEEN MICROFIBRA ...,TO,31,12,2017,49.99,0.277426,27.742645,49.990,2.0,99.98,20.18,72.74,52.56,26.280000
34585,000000000004269808 - CIF ULTRA RAP BANH S/CLOR...,TO,31,12,2017,3.99,0.189003,18.900344,3.990,2.0,7.98,1.10,5.82,4.72,2.360000

### Checagem de duplicidade no df principal

In [32]:
df_tratado

,SAP+NOME,UF,Dia,Mes,Ano,preço2,Mg %,Margem Líquida Real %,Preço,Vendas Reais Qtde,Vendas Reais $,Margem Líquida Real $,Venda Líquida Real $,CMV,CMV/QTD
0,000000000004243420 - AMACIANTE COMFORT CONCENT...,AL,2,1,2017,7.99,0.407011,40.701149,7.990,12.0,95.88,35.41,87.00,51.59,4.299167
1,000000000004243420 - AMACIANTE COMFORT CONCENT...,AM,2,1,2017,7.99,0.554937,55.493749,7.865,24.0,188.76,104.75,188.76,84.01,3.500417
2,000000000004243420 - AMACIANTE COMFORT CONCENT...,AP,2,1,2017,7.99,0.499373,49.937312,7.990,11.0,87.89,39.83,79.76,39.93,3.630000
3,000000000004263231 - JG CAMA QUEEN PRATA 150FI...,AP,2,1,2017,129.99,0.498731,49.873123,129.990,1.0,129.99,47.17,94.58,47.41,47.410000
4,000000000002158151 - T VISITA P BORDA DESIRE A...,BA,2,1,2017,4.99,0.416721,41.672131,4.190,10.0,41.90,12.71,30.50,17.79,1.779000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34581,000000000002166665 - FRONHA AVULSA ESTAMPADA A...,TO,31,12,2017,4.99,0.397732,39.773237,4.990,43.0,214.57,62.09,156.11,94.02,2.186512
34582,000000000002166719 - FRONHA AVULSA LISA ANDREZA,TO,31,12,2017,4.99,0.412655,41.265475,4.990,4.0,19.96,6.00,14.54,8.54,2.135000
34583,000000000004261082 - KIT CABIDE C/3 MADEIRA REV,TO,31,12,2017,1.99,0.146507,14.650706,10.990,14.0,153.86,16.40,111.94,95.54,6.824286
34584,000000000004266282 - JG CAMA QUEEN MICROFIBRA ...,TO,31,12,2017,49.99,0.277426,27.742645,49.990,2.0,99.98,20.18,72.74,52.56,26.280000
34585,000000000004269808 - CIF ULTRA RAP BANH S/CLOR...,TO,31,12,2017,3.99,0.189003,18.900344,3.990,2.0,7.98,1.10,5.82,4.72,2.360000

In [33]:
df_tratado.duplicated(subset=['SAP+NOME', 'UF', 'Ano', 'Mes', "Dia"]).value_counts()

False    34586
dtype: int64

### Criação da coluna da variável dummy de preço psicologico

In [34]:
df_tratado['DPPsic'] = ''
df_tratado.loc[df_tratado['Preço'] != df_tratado['preço2'], 'DPPsic'] = 0
df_tratado.loc[df_tratado['Preço'] == df_tratado['preço2'], 'DPPsic'] = 1

### Calculo de correlação entre quantidade de vendas e preço

In [35]:
df_corr = df_tratado.groupby(['UF', 'SAP+NOME'])[['Preço', 'Vendas Reais Qtde']].corr().reset_index()

In [36]:
df_corr

,UF,SAP+NOME,level_2,Preço,Vendas Reais Qtde
0,AC,000000000002158151 - T VISITA P BORDA DESIRE A...,Preço,1.000000,NaN
1,AC,000000000002158151 - T VISITA P BORDA DESIRE A...,Vendas Reais Qtde,NaN,NaN
2,AC,000000000002158154 - T VISITA P BORDA DESIRE A...,Preço,1.000000,-0.562500
3,AC,000000000002158154 - T VISITA P BORDA DESIRE A...,Vendas Reais Qtde,-0.562500,1.000000
4,AC,000000000002166665 - FRONHA AVULSA ESTAMPADA A...,Preço,1.000000,-0.517137
...,...,...,...,...,...
923,TO,000000000004269111 - DESINF LIQ PINHO SOL CITR...,Vendas Reais Qtde,NaN,NaN
924,TO,000000000004269808 - CIF ULTRA RAP BANH S/CLOR...,Preço,1.000000,-0.496182
925,TO,000000000004269808 - CIF ULTRA RAP BANH S/CLOR...,Vendas Reais Qtde,-0.496182,1.000000
926,TO,000000000004269883 - CIF ULT RAP TIRA LIMO C/C...,Preço,1.000000,-0.343479
927,TO,000000000004269883 - CIF ULT RAP TIRA LIMO C/C...,Vendas Reais Qtde,-0.343479,1.000000

In [37]:
df_corr.isnull().sum()

UF                    0
SAP+NOME              0
level_2               0
Preço                72
Vendas Reais Qtde    79
dtype: int64

In [38]:
df_corr = df_corr.loc[(df_corr['level_2'] == 'Vendas Reais Qtde') & (df_corr['Preço'].notnull()),\
                      ['UF', 'SAP+NOME','level_2','Preço']].sort_values(by='Preço', ascending=True).reset_index()

df_corr = df_corr[['UF', 'SAP+NOME', 'Preço']]

In [39]:
df_corr

     UF                                           SAP+NOME     Preço
0    RO  000000000004267279 - T VISITA DISNEY CARS SANT... -1.000000
1    SE  000000000004268705 - FRONHA AVULSA ESTAMPADA C... -0.885349
2    SP  000000000004269883 - CIF ULT RAP TIRA LIMO C/C... -0.878519
3    RJ  000000000004267048 - AMACIANTE COMFORT PURO CU... -0.871240
4    SP  000000000004248118 - AMACIANTE DOWNY LIRIOS DO... -0.869830
..   ..                                                ...       ...
414  PE  000000000004269111 - DESINF LIQ PINHO SOL CITR...  0.510949
415  SC  000000000004269111 - DESINF LIQ PINHO SOL CITR...  0.544581
416  PR  000000000004269111 - DESINF LIQ PINHO SOL CITR...  0.564917
417  RO  000000000004269111 - DESINF LIQ PINHO SOL CITR...  0.612372
418  RO  000000000004267503 - PANO SCOTT DURAMAX LIMPEZ...  0.707107

[419 rows x 3 columns]

### Cálculo do numero de observações por série

In [40]:
df_corr_obs = df_tratado.groupby(['UF', 'SAP+NOME'])['Dia'].count().reset_index()

In [41]:
df_corr_obs

     UF                                           SAP+NOME  Dia
0    AC  000000000002158151 - T VISITA P BORDA DESIRE A...    4
1    AC  000000000002158154 - T VISITA P BORDA DESIRE A...   10
2    AC  000000000002166665 - FRONHA AVULSA ESTAMPADA A...   16
3    AC    000000000002166719 - FRONHA AVULSA LISA ANDREZA   18
4    AC  000000000004243420 - AMACIANTE COMFORT CONCENT...   45
..   ..                                                ...  ...
459  TO  000000000004267503 - PANO SCOTT DURAMAX LIMPEZ...    7
460  TO  000000000004268705 - FRONHA AVULSA ESTAMPADA C...    6
461  TO  000000000004269111 - DESINF LIQ PINHO SOL CITR...   10
462  TO  000000000004269808 - CIF ULTRA RAP BANH S/CLOR...   31
463  TO  000000000004269883 - CIF ULT RAP TIRA LIMO C/C...   26

[464 rows x 3 columns]

### DF com correlação entre preço e quantidade e número de dias observadas por série

In [42]:
df_corr_final = pd.merge(df_corr_obs, df_corr, how='left', on=['UF', 'SAP+NOME'])
df_corr_final.rename(columns={"Preço":"Correlacao", "Dia":'NObs'}, inplace = True)
df_corr_final = df_corr_final.sort_values('NObs', ascending=False)
df_corr_final.reset_index(drop=True)

     UF                                           SAP+NOME  NObs  Correlacao
0    BA  000000000004243420 - AMACIANTE COMFORT CONCENT...   287   -0.617548
1    PE  000000000004243420 - AMACIANTE COMFORT CONCENT...   283   -0.752102
2    SP  000000000002158151 - T VISITA P BORDA DESIRE A...   275   -0.479322
3    SP  000000000002158154 - T VISITA P BORDA DESIRE A...   272   -0.413392
4    PA  000000000004243420 - AMACIANTE COMFORT CONCENT...   260   -0.639737
..   ..                                                ...   ...         ...
459  PA  000000000004270164 - DESINF LIQ PINHO SOL ORIG...     1         NaN
460  GO  000000000004267503 - PANO SCOTT DURAMAX LIMPEZ...     1         NaN
461  PI  000000000004267503 - PANO SCOTT DURAMAX LIMPEZ...     1         NaN
462  PI  000000000004269111 - DESINF LIQ PINHO SOL CITR...     1         NaN
463  MA  000000000004267503 - PANO SCOTT DURAMAX LIMPEZ...     1         NaN

[464 rows x 4 columns]

In [43]:
### CSV para dashboard
#df_corr_final.to_csv('../datasets/db_corr_nobs.csv', decimal = ',', sep=';', index=False)

### Acrescenta o número de semanas observadas ao df principal, renomeia SAP+NOME

In [44]:
df_tratado_final = pd.merge(df_tratado, df_corr_final[['UF', 'SAP+NOME', 'NObs']], 
                            how='left', left_on=['UF', 'SAP+NOME'], right_on=['UF', 'SAP+NOME'])

df_tratado_final.rename(columns={'SAP+NOME':'Produto', 'Vendas Reais Qtde':'QTD'}, inplace = True)

sap_nome = df_tratado_final['Produto'].str.split(" - ", n=1, expand=True)

df_tratado_final['SAP'] = sap_nome[0].apply(lambda x: x.lstrip('0'))

df_tratado_final['Produto'] = sap_nome[1]

In [45]:
df_tratado_final

,Produto,UF,Dia,Mes,Ano,preço2,Mg %,Margem Líquida Real %,Preço,QTD,Vendas Reais $,Margem Líquida Real $,Venda Líquida Real $,CMV,CMV/QTD,DPPsic,NObs,SAP
0,AMACIANTE COMFORT CONCENTRADO 500ML,AL,2,1,2017,7.99,0.407011,40.701149,7.990,12.0,95.88,35.41,87.00,51.59,4.299167,1,200,4243420
1,AMACIANTE COMFORT CONCENTRADO 500ML,AM,2,1,2017,7.99,0.554937,55.493749,7.865,24.0,188.76,104.75,188.76,84.01,3.500417,0,176,4243420
2,AMACIANTE COMFORT CONCENTRADO 500ML,AP,2,1,2017,7.99,0.499373,49.937312,7.990,11.0,87.89,39.83,79.76,39.93,3.630000,1,141,4243420
3,JG CAMA QUEEN PRATA 150FIOS MALIBU SANTI,AP,2,1,2017,129.99,0.498731,49.873123,129.990,1.0,129.99,47.17,94.58,47.41,47.410000,1,21,4263231
4,T VISITA P BORDA DESIRE AZUL 6238,BA,2,1,2017,4.99,0.416721,41.672131,4.190,10.0,41.90,12.71,30.50,17.79,1.779000,0,206,2158151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34581,FRONHA AVULSA ESTAMPADA ANDREZA,TO,31,12,2017,4.99,0.397732,39.773237,4.990,43.0,214.57,62.09,156.11,94.02,2.186512,1,123,2166665
34582,FRONHA AVULSA LISA ANDREZA,TO,31,12,2017,4.99,0.412655,41.265475,4.990,4.0,19.96,6.00,14.54,8.54,2.135000,1,133,2166719
34583,KIT CABIDE C/3 MADEIRA REV,TO,31,12,2017,1.99,0.146507,14.650706,10.990,14.0,153.86,16.40,111.94,95.54,6.824286,0,58,4261082
34584,JG CAMA QUEEN MICROFIBRA ANDREZA,TO,31,12,2017,49.99,0.277426,27.742645,49.990,2.0,99.98,20.18,72.74,52.56,26.280000,1,83,4266282
34585,CIF ULTRA RAP BANH S/CLORO SQUEEZE 500ML,TO,31,12,2017,3.99,0.189003,18.900344,3.990,2.0,7.98,1.10,5.82,4.72,2.360000,1,31,4269808

In [46]:
# df_tratado_final.to_csv('../datasets/df_tratado_final.csv', decimal = '.', sep=';', index=False)

### Criando df que será utilizado para ajustar o modelo - Produto individualizado

In [49]:
df_modelo_pi = df_tratado_final.loc[df_tratado_final['NObs'] >= 16, ['SAP', 'Produto', 'UF', 'Ano', 'Mes', 'Dia',
                                                                   'Preço', 'QTD', 'CMV/QTD',
                                                                   'DPPsic']]

In [50]:
df_modelo_pi

,SAP,Produto,UF,Ano,Mes,Dia,Preço,QTD,CMV/QTD,DPPsic
0,4243420,AMACIANTE COMFORT CONCENTRADO 500ML,AL,2017,1,2,7.990,12.0,4.299167,1
1,4243420,AMACIANTE COMFORT CONCENTRADO 500ML,AM,2017,1,2,7.865,24.0,3.500417,0
2,4243420,AMACIANTE COMFORT CONCENTRADO 500ML,AP,2017,1,2,7.990,11.0,3.630000,1
3,4263231,JG CAMA QUEEN PRATA 150FIOS MALIBU SANTI,AP,2017,1,2,129.990,1.0,47.410000,1
4,2158151,T VISITA P BORDA DESIRE AZUL 6238,BA,2017,1,2,4.190,10.0,1.779000,0
...,...,...,...,...,...,...,...,...,...,...
34581,2166665,FRONHA AVULSA ESTAMPADA ANDREZA,TO,2017,12,31,4.990,43.0,2.186512,1
34582,2166719,FRONHA AVULSA LISA ANDREZA,TO,2017,12,31,4.990,4.0,2.135000,1
34583,4261082,KIT CABIDE C/3 MADEIRA REV,TO,2017,12,31,10.990,14.0,6.824286,0
34584,4266282,JG CAMA QUEEN MICROFIBRA ANDREZA,TO,2017,12,31,49.990,2.0,26.280000,1
34585,4269808,CIF ULTRA RAP BANH S/CLORO SQUEEZE 500ML,TO,2017,12,31,3.990,2.0,2.360000,1

# SORTED()

In [51]:
aux = df_modelo_pi.copy()

lista_unicos = sorted(list(aux["Produto"].unique()))
aux["GrpProd"] = np.nan
grupo = 0
thresh = 52

# While

In [52]:
while len(lista_unicos) > 0:
    item = lista_unicos[0] 
    similaridades = process.extract(item, lista_unicos)
    for i in range(len(similaridades)):
        if (similaridades[i][1] >= thresh):
            aux.loc[aux["Produto"] == similaridades[i][0], "GrpProd"] = grupo
            lista_unicos.remove(similaridades[i][0])
    grupo += 1

## Validação

In [53]:
for i in range(len(aux["GrpProd"].unique())):
    print(f'grupo => {i}')
    print(aux.loc[aux["GrpProd"] == i]["Produto"].unique())

grupo => 0
['AMACIANTE COMFORT CONCENTRADO 500ML'
 'AMACIANTE DOWNY LIRIOS DO CAMPO 500ML'
 'AMACIANTE COMFORT PURO CUIDADO 500ML']
grupo => 1
['KIT CABIDE C/3 MADEIRA REV' 'CIF ULT RAP TIRA LIMO C/CLORO SQZ 500ML'
 'CIF ULTRA RAP BANH S/CLORO SQUEEZE 500ML']
grupo => 2
['DESINF LIQ PINHO SOL CITRUS LIMAO 500ML'
 'DESINF LIQ PINHO SOL ORIGINAL 500ML']
grupo => 3
['FRONHA AVULSA ESTAMPADA ANDREZA' 'FRONHA AVULSA LISA ANDREZA'
 'FRONHA AVULSA LISA CAMESA' 'FRONHA AVULSA ESTAMPADA CAMESA']
grupo => 4
['JG CAMA QUEEN PRATA 150FIOS MALIBU SANTI'
 'JG CAMA QUEEN MICROFIBRA ANDREZA']
grupo => 5
['PANO SCOTT DURAMAX LIMPEZA DIARIA C/5']
grupo => 6
['T VISITA P BORDA DESIRE AGUA 6243' 'T VISITA DISNEY CARS SANTISTA'
 'T VISITA DISNEY BELA SANTISTA']
grupo => 7
['T VISITA P BORDA DESIRE AZUL 6238']

In [54]:
sorted(aux["GrpProd"].unique())[-1]

7.0

## Realizando os agrupamentos

In [55]:
def agrupamentos(dataframe, threshold:float):
    """
    Descreve uma função que classifica os itens em grupos de similaridade utilizando fuzzy matching.
    
    dataframe -> dataframe que contém os itens a serem classificados]
    threshold -> grau de similaridade entre os nomes dos itens (0 a  100)
    """
    
    # Cria um vetor de itens únicos ordenados alfabeticamente
    lista_unicos = sorted(list(dataframe["Produto"].unique()))
    
    # Cria uma feature de NaN's chamada Grupo
    dataframe["GrpProd"] = np.nan
    grupo = 0
    
    # Percorre o nosso dataframe e faz o agrupamento entre os itens
    while len(lista_unicos) > 0:
        item = lista_unicos[0] 
        similaridades = process.extract(item, lista_unicos)
        for i in range(len(similaridades)):
            if (similaridades[i][1] >= threshold):
                dataframe.loc[dataframe["Produto"] == similaridades[i][0], "GrpProd"] = grupo
                lista_unicos.remove(similaridades[i][0])
        grupo += 1
    
    return dataframe

### Criando df que será utilizado para ajustar o modelo - Produto agrupado

In [31]:
df_modelo_pa = agrupamentos(aux, 55)

In [57]:
aux['PrXQtd'] = aux['Preço'] * aux['QTD'] 

aux['CMVXQtd'] = aux['CMV/QTD'] * aux['QTD']

aux['PPsicXQtd'] = aux['DPPsic'] * aux['QTD']

aux['PPsicXQtd'] = aux['PPsicXQtd'].astype(int)

df_modelo_pa = aux[['GrpProd', 'UF', 'Ano', 'Mes', 'Dia', 'QTD', 
                   'PrXQtd', 'CMVXQtd', 'PPsicXQtd']].groupby(['GrpProd', 'UF', 'Ano','Mes','Dia']).sum().reset_index()
          
df_modelo_pa['Preço'] = df_modelo_pa['PrXQtd'] / df_modelo_pa['QTD']

df_modelo_pa['CMV/QTD'] = df_modelo_pa['CMVXQtd'] / df_modelo_pa['QTD']

df_modelo_pa['DPPsic'] = df_modelo_pa['PPsicXQtd'] / df_modelo_pa['QTD']

df_modelo_pa.drop(columns=['CMVXQtd', 'PrXQtd', 'PPsicXQtd'], inplace = True)

In [58]:
df_modelo_pa.head(60)

    GrpProd  UF   Ano  Mes  Dia   QTD     Preço   CMV/QTD    DPPsic
0       0.0  AC  2017    1   20   4.0  7.990000  4.385000  1.000000
1       0.0  AC  2017    1   22   5.0  7.990000  4.384000  1.000000
2       0.0  AC  2017    3   31   4.0  4.990000  4.320000  1.000000
3       0.0  AC  2017    4    2   3.0  4.990000  4.316667  1.000000
4       0.0  AC  2017    4    5   3.0  4.990000  4.320000  1.000000
5       0.0  AC  2017    6   24   3.0  7.990000  6.580000  1.000000
6       0.0  AC  2017    7    1   2.0  9.990000  6.375000  1.000000
7       0.0  AC  2017    8    3   5.0  7.990000  6.582000  1.000000
8       0.0  AC  2017    8    4   4.0  7.990000  6.585000  1.000000
9       0.0  AC  2017    8    7   3.0  7.990000  6.583333  1.000000
10      0.0  AC  2017    8    8   3.0  7.990000  6.586667  1.000000
11      0.0  AC  2017    8   16  20.0  8.590000  6.586500  0.000000
12      0.0  AC  2017    8   17   3.0  8.323333  6.583333  0.000000
13      0.0  AC  2017    8   29   4.0  7.990000  6.585000  1.000000
14      0.0  AC  2017    8   31   7.0  7.990000  6.585714  1.000000
15      0.0  AC  2017    9    2   4.0  9.990000  6.557500  1.000000
16      0.0  AC  2017    9   28   4.0  8.990000  6.432500  1.000000
17      0.0  AC  2017   10    1   5.0  8.790000  6.508000  1.000000
18      0.0  AC  2017   10   10   2.0  9.990000  6.430000  1.000000
19      0.0  AC  2017   10   12   3.0  8.990000  4.816667  1.000000
20      0.0  AC  2017   10   21  11.0  7.990000  4.821818  1.000000
21      0.0  AC  2017   10   22   3.0  7.990000  4.873333  1.000000
22      0.0  AC  2017   10   23   5.0  7.990000  4.746000  1.000000
23      0.0  AC  2017   10   24   4.0  7.990000  4.822500  1.000000
24      0.0  AC  2017   10   25   6.0  7.990000  4.720000  1.000000
25      0.0  AC  2017   10   26   6.0  7.990000  4.738333  1.000000
26      0.0  AC  2017   10   27   8.0  7.990000  4.743750  1.000000
27      0.0  AC  2017   10   28  23.0  7.990000  4.784783  1.000000
28      0.0  AC  2017   10   29   8.0  7.990000  4.753750  1.000000
29      0.0  AC  2017   10   30   5.0  7.990000  4.724000  1.000000
30      0.0  AC  2017   11    1  10.0  7.990000  4.791000  1.000000
31      0.0  AC  2017   11    2  12.0  7.990000  4.796667  1.000000
32      0.0  AC  2017   11    3   3.0  9.990000  4.810000  1.000000
33      0.0  AC  2017   11    4  16.0  8.990000  4.965625  0.437500
34      0.0  AC  2017   11    5  13.0  8.990000  4.700769  1.000000
35      0.0  AC  2017   11    6  11.0  9.262727  4.750909  1.000000
36      0.0  AC  2017   11    8   5.0  8.990000  4.708000  1.000000
37      0.0  AC  2017   11    9   9.0  9.990000  4.820000  1.000000
38      0.0  AC  2017   11   11   4.0  8.990000  4.710000  1.000000
39      0.0  AC  2017   11   13   3.0  8.990000  4.713333  1.000000
40      0.0  AC  2017   11   14   9.0  7.990000  4.783333  1.000000
41      0.0  AC  2017   11   16   9.0  7.990000  4.748889  1.000000
42      0.0  AC  2017   11   17   9.0  7.990000  4.811111  1.000000
43      0.0  AC  2017   11   19   3.0  7.990000  4.706667  1.000000
44      0.0  AC  2017   11   21   7.0  7.990000  4.704286  1.000000
45      0.0  AC  2017   11   22   4.0  7.990000  4.705000  1.000000
46      0.0  AC  2017   11   24   5.0  6.990000  5.034000  1.000000
47      0.0  AC  2017   11   27   3.0  7.990000  5.036667  1.000000
48      0.0  AC  2017   11   28  22.0  7.180909  4.882273  0.772727
49      0.0  AC  2017   11   29   8.0  7.615000  4.916250  1.000000
50      0.0  AC  2017   11   30   7.0  7.990000  5.047143  1.000000
51      0.0  AC  2017   12    1   7.0  7.561429  4.900000  1.000000
52      0.0  AC  2017   12    2  10.0  7.390000  4.935000  1.000000
53      0.0  AC  2017   12    3   3.0  7.990000  5.046667  1.000000
54      0.0  AC  2017   12    4   2.0  7.990000  5.055000  1.000000
55      0.0  AC  2017   12    5   5.0  7.990000  5.030000  1.000000
56      0.0  AC  2017   12    7  10.0  7.490000  4.942000  1.000000
57      0.0  AC  2017   12    8   2.0  7.990000  5.025000  1.000000
58      0.0  AC  2017   12   10   6.0  7.323333  4.921667  1.000000
59      0.0  AC  2017   12   11  13.0  7.374615  4.927692  1.000000

In [59]:
df_modelo_pa.to_csv('../datasets/df_modelo_pa_diario.csv', decimal = '.', sep=';', index=False)

df_modelo_pi.to_csv('../datasets/df_modelo_pi_diario.csv', decimal = '.', sep=';', index=False)